### NumPy Check List

1) Simple ndarray creation
- create 1d array from a list
- create 1d array from a tuple
- create 1d array using arange
- create 2d array from normal distribution with mean = 0 and std = 1 in two ways
- create 3d array from random integers in range 0 - 100
- create an array from a list of string numbers. Then convert them into numbers 
- create an array of ones 3x4
- create an empty array with shape equals to array of ones
- create 2d array with ones on the main diagonal in 2 ways with shape 3,3

In [2]:
import numpy as np

my_lst = [i for i in range(10)]
my_tuple = tuple([i for i in range(50,60)])

arr_from_lst = np.array(my_lst)
arr_from_tuple = np.array(my_tuple)
arr_from_arange = np.arange(90,100)

display(arr_from_lst,arr_from_tuple,arr_from_arange)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
arr_from_dist_2d_1 = np.random.randn(3,2)
arr_from_dist_2d_2 = np.random.normal(0,1,(3,2))
arr_from_rand_int_3d = np.random.randint(0,100,(3,4,3))

arr_from_str = np.array(['1','2','3'])
arr_num = arr_from_str.astype(np.int)

arr_ones = np.ones((3,4))
arr_empty = np.empty_like(arr_ones)

arr_iden_1 = np.identity(3)
arr_iden_2 = np.eye(3,3)

display(arr_from_dist_2d_1,
        arr_from_dist_2d_2, 
        arr_from_rand_int_3d,
        arr_num, 
        arr_ones,
        arr_empty,
        arr_iden_1,
        arr_iden_2)

array([[-0.16814581, -2.00087117],
       [-1.62700891, -0.99987481],
       [-0.71567686, -0.33064997]])

array([[-0.50243261, -0.61182738],
       [ 1.46354552,  2.10853182],
       [-1.75343185,  1.77188671]])

array([[[82,  5, 26],
        [52, 52, 38],
        [53, 64, 59],
        [ 3, 15, 81]],

       [[17, 89, 91],
        [ 7, 33, 12],
        [ 8, 53, 55],
        [50, 77,  1]],

       [[82, 89, 20],
        [32, 32, 57],
        [22, 78, 73],
        [57, 76, 78]]])

array([1, 2, 3])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

2) NumPy Methods 
- check data type, dimesnion and shape of an array 
- change the type of an array 
- find mean/std and sum of an array 
- find all unique values in an array 
- sort an array
- check whether values from one array are presented in the second one 
- transpose an array 
- find dot product between two two arrays (matrices)
- raise to the power of 2 each element in an array 
- raise to the power of given sequence each element in an array 
- find min and max values of an array
- make element - wise comparison between two arrays and return min element in each position 
- calculate the square root of an array 
- checks whether there are missing values in an array 
- demonstrate difference between floor/ceil/rint 
- return sign of array elements
- make a copy of an array
- create a row - vector from 1D array in two ways 
- create a column - vector from 1D array in two ways
- concatenate 2 arrays in two different ways (by columns then by rows)
- stacks 2 arrays vertically,horizontaly and in depth 
- split an array horizontally, vertically and in depth (mention which methods exists for this task)

In [42]:
arr = np.arange(0,10).reshape(2,5)
arr = arr.astype('int64')
arr.mean()

4.5

In [106]:
display(arr_from_rand_int_3d.dtype,
        arr_from_rand_int_3d.ndim,
        arr_from_rand_int_3d.shape )

arr_str = arr_num.astype(np.str)
display(arr_str)

print(f'Mean is:{arr_from_rand_int_3d.mean()}'+'\n'+
      f'Std is: {arr_from_rand_int_3d.std()}'+'\n'+
      f'Sum is: {arr_from_rand_int_3d.sum()}' )

display(np.unique(arr_ones))

arr_from_rand_int_3d.sort()
display(arr_from_rand_int_3d)

display(np.in1d(arr_num,arr_from_rand_int_3d),
        arr_iden_1.T,
        np.dot(arr_ones,arr_from_rand_int_3d))

dtype('int32')

3

(3, 4, 3)

array(['1', '2', '3'], dtype='<U11')

Mean is:47.75
Std is: 28.296422035303333
Sum is: 1719


array([1.])

array([[[ 5, 26, 82],
        [38, 52, 52],
        [53, 59, 64],
        [ 3, 15, 81]],

       [[17, 89, 91],
        [ 7, 12, 33],
        [ 8, 53, 55],
        [ 1, 50, 77]],

       [[20, 82, 89],
        [32, 32, 57],
        [22, 73, 78],
        [57, 76, 78]]])

array([ True, False,  True])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[[ 99., 152., 279.],
        [ 33., 204., 256.],
        [131., 263., 302.]],

       [[ 99., 152., 279.],
        [ 33., 204., 256.],
        [131., 263., 302.]],

       [[ 99., 152., 279.],
        [ 33., 204., 256.],
        [131., 263., 302.]]])

In [105]:
display(np.square(arr_num),
        np.power(arr_num,[1,2,3]) )
        
print(f'Max is :{arr_from_rand_int_3d.max()}'+'\n'+
      f'Min is :{arr_from_rand_int_3d.min()}'+'\n')

display(np.minimum(arr_from_rand_int_3d,arr_num),
        np.sqrt(arr_from_rand_int_3d))

arr_with_nan = np.sqrt(arr_from_dist_2d_2)
display(np.isnan(arr_with_nan))

array([1, 4, 9], dtype=int32)

array([ 1,  4, 27], dtype=int32)

Max is :91
Min is :1



array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

array([[[2.23606798, 5.09901951, 9.05538514],
        [6.164414  , 7.21110255, 7.21110255],
        [7.28010989, 7.68114575, 8.        ],
        [1.73205081, 3.87298335, 9.        ]],

       [[4.12310563, 9.43398113, 9.53939201],
        [2.64575131, 3.46410162, 5.74456265],
        [2.82842712, 7.28010989, 7.41619849],
        [1.        , 7.07106781, 8.77496439]],

       [[4.47213595, 9.05538514, 9.43398113],
        [5.65685425, 5.65685425, 7.54983444],
        [4.69041576, 8.54400375, 8.83176087],
        [7.54983444, 8.71779789, 8.83176087]]])

c:\python 3.6.1\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in sqrt
  # Remove the CWD from sys.path while we load stuff.


array([[ True,  True],
       [False, False],
       [ True, False]])

In [110]:
value = 75.56
display(np.ceil(value),
        np.floor(value),
        np.rint(value),
        np.sign(arr_from_dist_2d_2))

copied_arr = arr_from_dist_2d_1.copy()
copied_arr

76.0

75.0

76.0

array([[-1., -1.],
       [ 1.,  1.],
       [-1.,  1.]])

array([[-0.16814581, -2.00087117],
       [-1.62700891, -0.99987481],
       [-0.71567686, -0.33064997]])

3.1) 1D Array Indexation
- select the first/last 5 elements 
- select every third element
- reverse the array
- every third element in reverse order
- from 5th till the beginning with step 2

The Array is given below

In [267]:
arr = arr_from_arange
arr

array([ 0,  0,  0, 93, 94, 95, 96, 97, 98, 99])

In [268]:
display(print(f'Original Array :{arr}'),
        arr[:5],
        arr[-5:],
        arr[::3],
        arr[::-1],
        arr[::-3],
        arr[-5::-2])

Original Array :[ 0  0  0 93 94 95 96 97 98 99]


None

array([ 0,  0,  0, 93, 94])

array([95, 96, 97, 98, 99])

array([ 0, 93, 96, 99])

array([99, 98, 97, 96, 95, 94, 93,  0,  0,  0])

array([99, 96, 93,  0])

array([95, 93,  0])

3.2) 2D Array Indexation
- select any column
- select each second column 
- the last 3 elements in each second column
- every second row in each second column  

The array is given below

In [171]:
np.random.seed(43)
arr = np.random.randint(0,500,(6,6))
arr

array([[324, 320, 255, 305, 277,  58],
       [ 16, 307, 145, 187, 347, 450],
       [366, 414, 343, 320, 291, 383],
       [434, 379, 459,  89, 449, 367],
       [ 34, 331, 194, 227, 373, 132],
       [292, 240, 373, 204, 216, 252]])

In [202]:
display(arr[:,0],
        arr[:,::2],
        arr[-3:,::2],
        arr[::2,::2])

array([324,  16, 366, 434,  34, 292])

array([[324, 255, 277],
       [ 16, 145, 347],
       [366, 343, 291],
       [434, 459, 449],
       [ 34, 194, 373],
       [292, 373, 216]])

array([[434, 459, 449],
       [ 34, 194, 373],
       [292, 373, 216]])

array([[324, 255, 277],
       [366, 343, 291],
       [ 34, 194, 373]])

3.3) 3D Array Indexation 
- select first two arrays
- select last row from the first array  
- select last rows from first two arrays 
- slice the center of all arrays. The result must have the shape (3x2x3)
- last columns of last 2 arrays in reverse order

The Array is given below

In [247]:
arr = arr_from_rand_int_3d
arr

array([[[ 5, 26, 82],
        [38, 52, 52],
        [53, 59, 64],
        [ 3, 15, 81]],

       [[17, 89, 91],
        [ 7, 12, 33],
        [ 8, 53, 55],
        [ 1, 50, 77]],

       [[20, 82, 89],
        [32, 32, 57],
        [22, 73, 78],
        [57, 76, 78]]])

In [248]:
display(arr[:2],
        arr[0,-1,],
        arr[:,1:3,:],
        arr[-2:,::-1,-1:]
       )

array([[[ 5, 26, 82],
        [38, 52, 52],
        [53, 59, 64],
        [ 3, 15, 81]],

       [[17, 89, 91],
        [ 7, 12, 33],
        [ 8, 53, 55],
        [ 1, 50, 77]]])

array([ 3, 15, 81])

array([[[38, 52, 52],
        [53, 59, 64]],

       [[ 7, 12, 33],
        [ 8, 53, 55]],

       [[32, 32, 57],
        [22, 73, 78]]])

array([[[77],
        [55],
        [33],
        [91]],

       [[78],
        [78],
        [57],
        [89]]])

Bool Indexation
- find all values greater or equla than 40 and find out how many of them
- find all values that greater or equal 24 and less or equall 77 and find out how many of them


The array is given below 

In [249]:
arr

array([[[ 5, 26, 82],
        [38, 52, 52],
        [53, 59, 64],
        [ 3, 15, 81]],

       [[17, 89, 91],
        [ 7, 12, 33],
        [ 8, 53, 55],
        [ 1, 50, 77]],

       [[20, 82, 89],
        [32, 32, 57],
        [22, 73, 78],
        [57, 76, 78]]])

In [266]:
display(arr[arr>=40],
        arr[arr>=40].shape[0],
         arr[(arr>=40) & (arr<=70)],
        arr[(arr>=40) & (arr<=70)].shape[0])

array([82, 52, 52, 53, 59, 64, 81, 89, 91, 53, 55, 50, 77, 82, 89, 57, 73,
       78, 57, 76, 78])

21

array([52, 52, 53, 59, 64, 53, 55, 50, 57, 57])

10