### NumPy 
NumPy a library for high - productive scientific calculations and data analysis. It provides fast vector operations for data cleaning and reflowing, set selection, different transformations and others.

Key element in NumPy is **ndarray object** which represents n - dimensional array. Ndarray is fast and flexible container for huge datasets storage. Arrays allows to execute different operations on whole data blocks as well as scalars. 

**Ndarray can store only one data type**

### Array Creation
- **np.array( list )** - creates a NumPy 1D array from a list
- **np.array( nested_list )** - creates a multivariate array
- **np.arange( shape )** - like range bur returns an array
- **np.linspace( interval )** - returns evenly spaced numbers over a specified interval: start (inc) stop (inc) + step
- **np.asarray( data, dtype )** transforms given data into ndarray object
- **np.full( shape , scalar)** - creates an array with given shape filled with provided scalar value
- **np.zeros( shape )** - creates an array with zeroes
- **np.ones ( shape )** - creates an array with ones
- **np.emty ( shape )** - creates an empty array, not necessearily zeroes
- **np.emty_like( arr )** - takes another array,takes into account its dimension and creates an empty array with the dimension 
- **np.ones_like( arr )** - similar to np.emty_like ( )
- **np.eye( shape )** - creates 2d array with one on the main diagonal 
- **np.identity( shape )** - creates 2d array with one on the main diagonal 
- **arr[ np.newaxis, : ]** - creates a row vector using 1D array
- **arr[ : , np.newaxis ]** - creates a column vector using 1D array 

### Array Creation using Random
There are some differences between methods in this module which must be known
- **np.random.rand( shape )** - random samples from Normal Distribution in range 0 (inc) - 1 (excl)
- **np.random.randint( shape )** - random integers from low (inc), high (exc)
- **np.random.randn( shape )** - random samples from Normal Distribution with mean = 0 and std = 1
- **np.random.normal( shape )** - random samples from Normal Distribution where mean and std can be customized
- **np.random.random( shape )** - similar to np.random.rand( )
- **np.random.choice( arr, size )** - randomly selects samples from 1D array according to provided size

### Array Data Types
**dtype** is a special object which contains necessary information of ndarray for data interpretation.

**Each array** can have **only one data type**

All available types can be obtained from the following command: **np.ctypes( )** - list all types
- **int8, uint8** -   1byte, 8 digit postions (unsigned takes only positive values)
- **int16, uint16** - 2 bytes, 16 digit postitions
- **int32, uint32** - 4 bytes, 32 digit positions
- **int64, uint64** - 8 bytes, 64 digit positions
- **float16** - half - precision - floating - point
- **float32** - one precision - floating point
- **float64** - double precision - floating - point 
- **float128** - Extended precision floating point
- **complex64,128,256** - complex numbers
- **bool** - True/False
- **string_** - string type with fixed length 
- **unicode_** -unicode type for strings with fixed length 

Some methods:
- **arr.dtype** - returns data type  
- **arr.astype( type )** changes a type of an array

### Array Indexation
**1D Array** <br>
Behaves like an ordinary list. Indexation is the same. All slicing of an array are **views**!!

**Views are not copies, thus any changes in views changes original array. It is very important**
- **arr[ : : ]** - only rows slicing 

**2d Array** <br>
Has 2 dimensions 0 - axis (rows), 1 - axis (columns)
- **arr[ : :, : : ]** - rows and columns slicing

**3D Array**<br>
Has 3 dimensions depth (how many arrays to choose), rows and columns
- **arr[ : :,: :, : : ]** - depth, rows and columns slicing 

For Multidimensional arrays number of axes is proportional to the dimension 

### Bool Indexation 
Returns a result accoridng to a provided condition. **Always returns a copy**. This method is also called boolean masks.
It is interresting but when we provide a statement, for example x < 3, NumPy interpretes it as np.less(x, 3). Thus, it operates **ufunctions** inside.

Operators are: & (and) | (or) ^ (xor) ~ (not) and they operate seprate bits inside **each object** whereas and,or,xor operate on the whole object
- **arr[ condition ]** 
- **np.where( condition, val_1, val_2 )** - substitute values according to specified condition. If True val_1, otherwise val_2
- **np.count_nonzero( condition )** - can be used to count number of True statements. np.sum() is more preferable
- **np.all / any ( )** - checks if all or any elements are True


### Fancy Indexing 
The main difference is that it takes an **array of indexes** and final shape will be equal to the shape of indexes array.
**Always creates a new array**
1D Array:
- **arr[ arr( indexes ) ]** - selects elemetns according to provided array of indexes.
2D Array:
- **arr[ arr( rows_idxs ), arr( columns_idxs ) ]** - selects elements according to the following combination (row_idx,col_idx)...
Fancy Indexing can be combined with ordinary indexes
- **arr[ indx, arr( indxs ) ]** - selects elements according to the following combination (indx, arr[0]), (indx,arr[1])...


- **arr[ [rows_idxs ] ] [:, [ cols_idxs ] ]** - combination is different (row_1,col_1), (row_1,col_2)...
- **arr[ np.ix_( [ rows_idxs ], [ cols_idxs ] )]** similar to above method

### Array Dimension Methods 
- **arr.shape** - returns shape 
- **arr.ndim** - returns dimension of an array 
- **arr.size** - returns number of variables in an array
- **arr.T** - transposes an array 
- **arr.reshape( )** - reshapes an array. If one of the axes equals **-1** then appropriate shape will be computed aoutomatically
- **arr.ravel( arr )** - flattens an array of any dimension into 1D array
- **np.swapaxes( )** - swaps two axes 

### Array Cloning / Copying
- **np.copysign( signs )** - copies signs from a provided array
- **np.repeat( arr, times )** - returns 1D array from an array of any dimension where each element will be repeated according to times param 
- **arr.copy( )** - copies an array

### Array Unification Methods
- **np.stack( arrays )** - stacks several arrays into a big one 
- **np.concatenate( [ arrays ], axis )** concatenates several arrays
- **np.vstack( [ arrays ] )** concatenates along columns (1 axis )
- **np.hstack( [ arrays ] )** - concatenates along rows ( 0 axis )
- **np.dstack( [ arrays ] )** - concatenates along depth or 3d axis ( 2 axis ) 

### Array Splitting Methods 
- **np.split( arr, axis )** - splits an array into multiple sub-arrays according to provided axis
- **np.hsplit( arr )** - splits an array into multiple sub-arrays horizontally (column-wise, axis = 1) 
- **np.vsplit( arr )** - splits an array into multiple sub-arrays vertically (row-wise, axis = 0) 
- **np.dsplit( arr )** - splits an array into multiple sub-arrays along the 3d axis ( depth )

### Array Methods 
- **arr.sort( )** - sorted array
- **arr.unique( )** - returns only unique values
- **np.in1d ( )** - checks if values from one array are presented in another  
- **arr.itemsize( )** - returns how much **each array elemet** takes up memory in bytes
- **arr.nbytes( )** - returns how much the whole array takes up memory in bytes
- **np.at( )** - applies provided operator for provided element indexes

### Array Sorting 
- **np.searchsorted( arr , values)** - returns indexes of where elements should be inserted to maintain array order 
- **np.sort( arr, axis )** - sorts an array. It uses quicksort by default, complexity O[NlogN]. Axis = 0 sorts by columns
- **np.argsort( arr )** - returns indexes of sorted array 
- **np.partition( arr, val_indx )** - read docum

### Transpose
It changes the form of matrix
- **arr.T** - transpose operation
- **arr.transpose()** - transpose oeration
- **np.dot( mtrx_1, matrx_2 )** - dot product of 2 matrices

### Ufunctions
Cycles in Python are incredibly slow. This is due to the fact that data type of a result of any operation must be checked before saving. This leads to slowness.Luckily, NumPy arrays must have a certain data type when initializing and data is vectorized.
Vector operations in NumPy are realized by **universal functions ufunc**. 
These functions executes element-wise operations, incredibly fast and can be applied to arrays of any dimension.
There are several types of ufunctions **unary** and **binary**

Typical **binary** mathematical operations such as: **+,-,*,/,//** (element - wise)
- **np.add / substract / multiply / devide( arr, value, out )** - out can be used to save the results in a created array instead of temporary, **it saves memory**
- **np.floor_divide( )** - similart to a // b
- **np.maximum( x, y )** - element - wise comparison between arrays
- **np.ufunc.reduce( arr )** - reduces dimension by one, by applying ufunc along one axis (dim - 1)
- **np.ufunc.accumulate( arr)** - accumulates the result of applying the ufunc to all elements
- **np.cumsum( arr )** - returns the cumulative sum of the elements along a given axis
- **np.cumprod( arr )** - returns the cumulative product of the elements along a given axis
- **np.ufunc.outer( arr_1, arr_2 )** - applies an ufunc to all pairs (a, b).

Simple **unary** operations: sign change (-x), raising to the power and % 
- **np.negative( arr )** - changes signs
- **np.power( arr, value or list_of_powers )** - raises an array to the given power or list of powers
- **np.mod( arr )** - similar to a % b
- **np.abs( )** - returns absolute value
- **np.absolute( )** - similar to np.abs
- **np.square( )** - computes square of each element
- **np.sqrt( arr )** - square root

- **np.sign( )** - returns sign of each elemet
- **np.exp( arr )** - exponent of x
- **np.2exp( arr )** - e^2x
- **np.sin / cos / tan( arr )** - computes trigonometric functions of an array
- **np.log, log10, log2, log1p** - understandable 
- **np.ceil( )** - round operation. Next whole number
- **np.floor( )** - round operation 
- **np.rint( )**- rounds till the closest int 
- **np.isnan( )** - checks NaN values 

### Aggregation Functions
- **arr.sum / prod / mean / median / std / var ( axis )** - typical operations.**Axis determines how values will be aggregated** . **axis = 0  is columns**
- **arr.min / max ( )** - returns max and min element of an array
- **arr.argmin / argmax ( )** - returns an index of min or max element 
- **np.percentile( )** - computes quantiles of the elements

!! In order to not include **NaN values** provide nan before any of above commands. For example, **arr.nansum**

### Array Broadcasting
Broadcastig allows to apply binary operations such as addition,division and so on to arrays of different shape. For example, we want to add two arrays with different shape arr_1 (3,0) and arr_2 (3,3). In this case, we can imagine that arr_1 transforms into arr (3,3) with the same values in each row and then being added. Actually, transformation is not happening, it is just a convinience for our brain.

There are rules which must be followed:
- If **dimension** of two arrays is different, array with less dimension is being brodcasted with the same values to the equal shape
- If **shape** of two arrays is not equal, axis with less dimension is being extended till it mathces dimension of another array.
- If shapes still different, an error occurs


In [1]:
import numpy as np

### Array Creation

In [75]:
# Univariate Array Creation 
lst = [1,2,6,10]
array = np.array(lst)
display(lst)

# Mulivariate Array Creation
nested_lst = [[10,23,1],[20,11,6]]
array_nested = np.array(nested_lst)
display(array_nested)

# Transformation into array
data = ['1','2','3']
array = np.asarray(data, dtype = np.float32 )
display(array)

# Array with only ones creation
ones = np.ones((3,3))
display(ones)

# Array with only zeroes creation
zeros = np.zeros((3,3))
display(zeros)

# Empty Array Creation
empty = np.empty((3,3))
display(empty)

# Emty_like
array = np.arange(5)
empty = np.empty_like(array)
display(empty)

# Zeroes_like
array = np.ones((2,2))
zeroes = np.zeros_like(array)
display(zeroes)

# Identity
identity = np.identity(3)
display(identity)

# Eye
eye = np.eye(3,3)
display(eye)

[1, 2, 6, 10]

array([[10, 23,  1],
       [20, 11,  6]])

array([1., 2., 3.], dtype=float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

array([-964267536,        358, -964294136,        358, -969345232])

array([[0., 0.],
       [0., 0.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Dimensions Methods 

In [98]:
# Initial 3D array
arr = np.random.randint(0,100,(3,4,3))

display(arr.ndim,
        arr.shape,
        arr.ravel(),
        arr.reshape(3,-1,2))

3

(3, 4, 3)

array([54, 35, 58, 75, 99, 38, 88, 72,  5, 64, 13, 41,  6, 58, 44, 11, 98,
       10, 15, 31, 33, 51,  7, 58,  9, 15, 35, 61, 99, 70, 47, 71, 18, 35,
        0, 40])

array([[[54, 35],
        [58, 75],
        [99, 38],
        [88, 72],
        [ 5, 64],
        [13, 41]],

       [[ 6, 58],
        [44, 11],
        [98, 10],
        [15, 31],
        [33, 51],
        [ 7, 58]],

       [[ 9, 15],
        [35, 61],
        [99, 70],
        [47, 71],
        [18, 35],
        [ 0, 40]]])

### Array Indexation 
1D Array

In [114]:
array = np.arange(10)
print('Original array:'+str(array))

# Slicing Demonstration
display(array[5:])
display(array[5:8])

# Important note!
array_slice = array[1:4]
print('Original slice :'+str(array_slice))
array_slice[1:] = 1000
print('Modified slice: '+str(array_slice))
# Slice is not copy. All changes in the sice will affect original array
print('Original array:'+str(array))

Original array:[0 1 2 3 4 5 6 7 8 9]


array([5, 6, 7, 8, 9])

array([5, 6, 7])

Original slice :[1 2 3]
Modified slice: [   1 1000 1000]
Original array:[   0    1 1000 1000    4    5    6    7    8    9]


2D Array

In [138]:
# 2D Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Simple Selection
print(arr[2])
print(arr[1,1])
print(arr[1][1])
print('\n')

# 2D Array Slicing 
print(arr[1:,1:])
print('\n')
print(arr[:,1:])

[7 8 9]
5
5


[[5 6]
 [8 9]]


[[2 3]
 [5 6]
 [8 9]]


3D Array

In [134]:
# 3D Array. It has dimension 2x2x3
arr = np.array( [ [[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]] ])
print(arr)
print(arr.shape)
print(arr[0][0][1])
print(arr[1][0][1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
2
8


### Bool Indexation 

In [163]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.randn(names.shape[0],4)

print(names == 'Bob')
print('\n')
condition = names == 'Bob'
# Now, according to above condition we will select rows with True condition 
selection = data[condition]
print(selection)
print('\n')
new_sel = selection[0,:] 
new_sel = 0
print(new_sel)
print('\n')
print('Original Slice: '+str(selection))

[ True False False  True False False False]


[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]]


0


Original Slice: [[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]]


In [175]:
# Set values below zero to zero 
data[data<0]= 0
data

array([[0.        , 0.99734545, 0.2829785 , 0.        ],
       [0.        , 1.65143654, 0.        , 0.        ],
       [1.26593626, 0.        , 0.        , 0.        ],
       [1.49138963, 0.        , 0.        , 0.        ],
       [2.20593008, 2.18678609, 1.0040539 , 0.3861864 ],
       [0.73736858, 1.49073203, 0.        , 1.17582904],
       [0.        , 0.        , 0.9071052 , 0.        ]])

### Fancy Indexing 

In [183]:
arr = np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [194]:
# Rows Selection 

print(arr[[0,2,4,6]])
print('\n')

print(arr[ [1,5,7,2],[0,3,1,2] ]) 
print('\n')

print(arr[[1,5,7,2]][:,[0,3,1,2]])
print('\n')

print(arr[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 0  1  2  3]
 [ 8  9 10 11]
 [16 17 18 19]
 [24 25 26 27]]


[ 4 23 29 10]


[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


### Transpose

In [199]:
arr = np.arange(12).reshape(2,6)
print(arr)
print('\n')
print(arr.T)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [226]:
matrx_1 = np.arange(15).reshape(3,5)
matrx_2 = np.random.randn(5,3)
display(matrx_1)
display(matrx_2)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

array([[ 0.88389311,  0.19586502,  0.35753652],
       [-2.34326191, -1.08483259,  0.55969629],
       [ 0.93946935, -0.97848104,  0.50309684],
       [ 0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266]])

In [228]:
dot_prod = np.dot(matrx_1,matrx_2)
dot_prod

array([[ -2.41314696,  -5.44088338,  -5.03235332],
       [ -6.94065579, -17.37266104,  -6.79527281],
       [-11.46816461, -29.30443869,  -8.5581923 ]])

In [233]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

### Arrays Unification

In [22]:
# Arrays Creation 
arr_1 = np.arange(8).reshape(2,4)
arr_2 = np.arange(30,38).reshape(2,4)

# Concatenate along rows (axis = 0)
con_row_arr = np.concatenate([arr_1, arr_2])

# Concatenate along columns (axis = 1)
con_col_arr = np.concatenate([arr_1, arr_2],axis=1)

# vstack
v_stacked_arr = np.vstack([arr_1, arr_2])

# hstack 
h_stacked_arr = np.hstack([arr_1, arr_2])

# dstack
d_stacked_arr = np.dstack([arr_1, arr_2])

display(con_row_arr,con_col_arr,
        v_stacked_arr,h_stacked_arr,d_stacked_arr)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [30, 31, 32, 33],
       [34, 35, 36, 37]])

array([[ 0,  1,  2,  3, 30, 31, 32, 33],
       [ 4,  5,  6,  7, 34, 35, 36, 37]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [30, 31, 32, 33],
       [34, 35, 36, 37]])

array([[ 0,  1,  2,  3, 30, 31, 32, 33],
       [ 4,  5,  6,  7, 34, 35, 36, 37]])

array([[[ 0, 30],
        [ 1, 31],
        [ 2, 32],
        [ 3, 33]],

       [[ 4, 34],
        [ 5, 35],
        [ 6, 36],
        [ 7, 37]]])

### Array Splitting 

In [35]:
# vsplit
upper, lower = np.vsplit(v_stacked_arr,2)
print(f'Upper array is:\n {upper}\n Lower array is:\n {lower}')
print('\n')

# hsplit
left, right = np.hsplit(v_stacked_arr,2)
print(f'Upper array is:\n {left}\n Lower array is:\n {right}')
print('\n')

# Can split not only by a number but by necessary sequence
arr = np.arange(10).reshape(2,5)
left, centred, right = np.hsplit(arr,[2,4])
print(f'Left array is:\n {left}\n Centred array is:\n{centred}\n Right array is:\n{right}')
print('\n')

# dsplit 
inner, outer = np.dsplit(d_stacked_arr,2)
print(f'Inner array is:\n {inner}\n Outer array is:\n {outer}')

Upper array is:
 [[0 1 2 3]
 [4 5 6 7]]
 Lower array is:
 [[30 31 32 33]
 [34 35 36 37]]


Upper array is:
 [[ 0  1]
 [ 4  5]
 [30 31]
 [34 35]]
 Lower array is:
 [[ 2  3]
 [ 6  7]
 [32 33]
 [36 37]]


Left array is:
 [[0 1]
 [5 6]]
 Centred array is:
[[2 3]
 [7 8]]
 Right array is:
[[4]
 [9]]


Inner array is:
 [[[0]
  [1]
  [2]
  [3]]

 [[4]
  [5]
  [6]
  [7]]]
 Outer array is:
 [[[30]
  [31]
  [32]
  [33]]

 [[34]
  [35]
  [36]
  [37]]]


In [35]:
# Create a row vector from an array using reshape
arr = np.array([1,2,3])
row_vec = arr.reshape(1,3)
display(arr.shape,row_vec.shape)

# Create a row vector from an array using new axis
row_vec = arr[np.newaxis,:]
display(row_vec.shape)

# Create a column vector from an array 
col_vec = arr.reshape(3,1)
display(col_vec.shape)

# Create a column vector from an array  using new axis
col_vec = arr[:,np.newaxis]
display(col_vec.shape)

(3,)

(1, 3)

(1, 3)

(3, 1)

(3, 1)

### Ufunctions
Binary functions

In [71]:
# Reduce
arr = np.arange(1,11)
print(np.multiply.reduce(arr))

# accumulate
print(np.add.accumulate(arr))

# sum, prod, cumsum, cumprod
display(np.sum(arr),
        np.prod(arr),
        np.cumsum(arr),
        np.cumproduct(arr))

3628800
[ 1  3  6 10 15 21 28 36 45 55]


55

3628800

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

### Array broadcasting 

In [107]:
arr_1 = np.arange(4)
arr_2 = np.arange(4)[:,np.newaxis]
brdcs_arr = arr_1 + arr_2
print(f'First array shape: {arr_1.shape}\nSecond array shape:{arr_2.shape}'+'\n'+
      f'Broadcasting result:\n{brdcs_arr}\nFinal Shape:{brdcs_arr.shape}')

First array shape: (4,)
Second array shape:(4, 1)
Broadcasting result:
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
Final Shape:(4, 4)


### Fancy Indexing
1D

In [97]:
arr = np.random.randint(0,101,10)

indx_1 = [5,4,0,1] # the first shape
indx_2 = np.random.randint(0,6,(3,2)) # the second shape

display(arr[indx_1],arr[indx_2])

array([48, 68, 59, 27])

array([[ 2, 27],
       [68, 28],
       [68,  2]])

2D

In [100]:
arr = np.random.randint(0,101,(3,4))
# The first shape
rows_1 = [0,2,1,2,0]
cols_1 = [1,3,2,1,3]
# The second shape
rows_2 = np.random.randint(0,3,(3,3))
cols_2 = np.random.randint(0,4,(3,3))
display(arr[rows_1,cols_1],arr[rows_2,cols_2])

array([19, 82, 14, 15, 30])

array([[19,  5, 15],
       [15, 15, 82],
       [65, 15, 19]])

Combination of Fancy Indexing and Ordinary Indexing

In [103]:
indx = 2
arr_indx = [0,2]
display(arr,arr[2,arr_indx])

array([[47, 19, 14, 30],
       [43, 15, 14,  5],
       [65, 15, 22, 82]])

array([65, 22])

In [109]:
x = np.random.rand(100)

bins = np.linspace(-5,5,20)
counts = np.zeros_like(bins)

i = np.searchsorted(bins,x)

### Array Sorting 

In [133]:
# np.searchsorted()
arr = np.arange(10)

# what will be the index if i want to insert a value and preserve the array order?
indx = np.searchsorted(arr,5,side='left')

# in case of several values
indxs = np.searchsorted(arr,[4,1,9],side='left')
display(arr,indx,indxs)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5

array([4, 1, 9], dtype=int64)

Insertion Sort (Complexity N^2)

In [155]:
# np.argmin()
np.random.seed(12)
arr = np.random.randint(40,77,10)
print(arr)

def inser_sort(arr):
    for i in range(len(arr)):
        swap_elem = i + np.argmin(arr[i:])
        arr[i],arr[swap_elem] = arr[swap_elem], arr[i]
    return arr

inser_sort(arr)

[51 67 46 42 43 43 52 62 45 53]


array([42, 43, 43, 45, 46, 51, 52, 53, 62, 67])

Random Sorting ( Complexity N*N!) almost not used

In [176]:
def bogosort(arr):
    while np.any(arr[:-1] > arr[1:]):
        np.random.shuffle(arr)
    return arr
arr = [2,5,10,23,12]
bogosort(arr)

[2, 5, 10, 23, 12]

In [207]:
np.random.seed(12)
arr = np.random.randint(40,99,(4,4))
print('Original array:\n', arr)

# np.sort()
print('Sorted by columns:\n',np.sort(arr,axis=0))
print('Sorted by rows:\n',np.sort(arr,axis=1))

# np.argsort()
print('Sorted array indexes by columns:\n', np.argsort(arr,axis=0))
print('Sorted array indexes by rows:\n',np.argsort(arr,axis=1))
print('\n')

# np.partition()

# Simple 1D Array 
arr_1d = np.random.randint(0,22,9)
print('1D Array is:\n',arr_1d)
print('Partitioned 1D Array is:\n',np.partition(arr_1d,4))
print('\n')

# 2D Array
arr_2d = np.random.randint(0,101,(4,5))
print('2D Array is:\n',arr_2d)
print('Partitioned 2D Array is:\n',np.partition(arr_2d,2,axis=1))

Original array:
 [[51 67 46 89]
 [42 43 43 52]
 [88 62 89 92]
 [45 53 65 74]]
Sorted by columns:
 [[42 43 43 52]
 [45 53 46 74]
 [51 62 65 89]
 [88 67 89 92]]
Sorted by rows:
 [[46 51 67 89]
 [42 43 43 52]
 [62 88 89 92]
 [45 53 65 74]]
Sorted array indexes by columns:
 [[1 1 1 1]
 [3 3 0 3]
 [0 2 3 0]
 [2 0 2 2]]
Sorted array indexes by rows:
 [[2 0 1 3]
 [0 1 2 3]
 [1 0 2 3]
 [0 1 2 3]]


1D Array is:
 [11 10  0 21  8 12 13 18  3]
Partitioned 1D Array is:
 [ 0  3  8 10 11 12 13 18 21]


2D Array is:
 [[ 62 100  35  33  30]
 [ 63  96  18  86  50]
 [ 80  84   6  73  45]
 [ 30  32  27  59  89]]
Partitioned 2D Array is:
 [[ 30  33  35 100  62]
 [ 18  50  63  86  96]
 [  6  45  73  80  84]
 [ 27  30  32  59  89]]
